OPTION _EXPLICIT
$IF WIN THEN
    DECLARE LIBRARY ".\preproc"
$ELSE
    DECLARE LIBRARY "./preproc"
    $END IF
    FUNCTION __VARIABLE_NAME$ (BYVAL Variable AS _OFFSET)
    FUNCTION __FUNCTION_NAME$ ()
    FUNCTION __FUNCTION_NAME_FULL$ ()
    FUNCTION __SRC_LINE& ()
    FUNCTION __SRC_FILE$ ()
    FUNCTION __STATIC_COUNT& ()
    FUNCTION __COMPILE_DATE$ ()
    FUNCTION __COMPILE_TIME$ ()
    FUNCTION __SRC_LAST_EDIT$ ()
    $IF WIN THEN
    FUNCTION __WIN32% ()
    FUNCTION __WIN64% ()
    $END IF
    FUNCTION __INC_DEPTH% ()
    FUNCTION __BASE_FILE$ ()
END DECLARE

PRINT __STATIC_COUNT; ") This program was compiled at "; __COMPILE_TIME; " on "; __COMPILE_DATE
PRINT __STATIC_COUNT; ") Last edit    :", __SRC_LAST_EDIT
PRINT __STATIC_COUNT; ") Source file  :", __SRC_FILE
PRINT __STATIC_COUNT; ") Base file    :", __BASE_FILE
PRINT __STATIC_COUNT; ") Architecture :",
$IF WIN THEN
    IF __WIN64 THEN
    PRINT "64 BIT"
    ELSEIF __WIN32 THEN
    PRINT "32 BIT"
    END IF
$END IF
PRINT __STATIC_COUNT; ") Incl. depth  :", __INC_DEPTH
PRINT

PRINT __STATIC_COUNT; ") Function     :", __FUNCTION_NAME
PRINT __STATIC_COUNT; ") Function Sig.:", __FUNCTION_NAME_FULL
DIM var AS INTEGER
PRINT __STATIC_COUNT; ") var in QB64 = "; __VARIABLE_NAME(var); " in C++"
